### ISSUE TITLE
Test cases are failing

### ISSUE THREAD

**Issue by kholia** [darjeeling/python-blake2#1]
I have tried running the test cases on 32-bit as well as 64-bit Linux machines but they fail.

```
✗ python2 test.py
Traceback (most recent call last):
  File "test.py", line 12, in blake2b
    assert blake2.blake2("blake2") == '22ccfc5a19a58358eb07a89e9b2c29356fff5ed0a50364ae1391649fc6152a2a700fc712f1ba031f3ee6e64736feacf49308755eabc9719352b54192b820f435'
AssertionError
```

The correct hash of "blake2" should be `4245af08b46fbb290222ab8a68613621d92ce78577152d712467742417ebc1153668f1c9e1ec1e152a32a9c242dc686d175e087906377f0c483c5be2cb68953e`

This correct hash matches the actual output of your code and also the output of my JtR plug-in.

**Comment by darjeeling** [comment]
well,
I tried another machines. it make another hash on each machine. haha.
gcc 4.1.2 - 64bit Intel X5645 python 2.4.3  : 7b8e735071202f30f3615f0e24d8abbe2a7f9697d131bc92775bbcf3e45ece1b356df48ecaa3f0fdba26bcc7cee588c63d336443a9e4540858306627f5cf17bc

**Comment by kholia** [comment]
I can confirm that the reference implementation does not have this problem.

**Comment by darjeeling** [comment]
ok I'll try source update.

**Comment by darjeeling** [comment]
got the reason.
it's because given key parameter is differently generated in blake2b_init.
I dunno why. but with same given key I got the same result.

**Comment by darjeeling** [comment]
with the same key 

```
A lib.linux-x86_64-2.5 b202b477a797e984e6a2b976ca4cb7d3944004b3ef6cde80341c7853a2dd7e2f9e08cda6d7372812cf75e8c7741fb656cec3a119772e2e715cebc76433fafd4d
B lib.linux-x86_64-2.7 b202b477a797e984e6a2b976ca4cb7d3944004b3ef6cde80341c7853a2dd7e2f9e08cda6d7372812cf75e8c7741fb656cec3a119772e2e715cebc76433fafd4d
C lib.linux-i686-2.6 b202b477a797e984e6a2b976ca4cb7d3944004b3ef6cde80341c7853a2dd7e2f9e08cda6d7372812cf75e8c7741fb656cec3a119772e2e715cebc76433fafd4d
```

without key

```
A lib.linux-x86_64-2.5 fa89b8c8154b3f57c5ddfde672e6ae8fbf5276de3407770d60e0802f8b4ba08c88e5152e9ac97ab3714f561efa8ba47267e55c56a0da4074cfcaefbe9ae6d951
B lib.linux-x86_64-2.7 4245af08b46fbb290222ab8a68613621d92ce78577152d712467742417ebc1153668f1c9e1ec1e152a32a9c242dc686d175e087906377f0c483c5be2cb68953e
C lib.linux-i686-2.6 6e5ba2ba88ec32b550bba9f44f48ad2ae56a805b597d052034bb56614fe0f61525cb9aaba6129df96d2542f10ecad4727f934d90928fb63b2d20a27ec6fdf31f
```

**Comment by darjeeling** [comment]
I think giving default key value to fixed value is right decision.
how do you think about it?

**Comment by kholia** [comment]
You can also reuse standard test vectors published by the BLAKE2 team.

**Comment by darjeeling** [comment]
fixed

I'll update to use test vectors by BLAKE2 team.

**Comment by darjeeling** [comment]
make the default key NULL to ""
